version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-abtest
    restart: always
    command: --port 6379
    expose:
      - "6379"
    volumes: 
      - .dbdata:/var/lib/redis 
    ports: 
      - 6379:6379
